[build]
  publish = "dist"
  command = "npm run build"

# SEO-friendly service page redirects
[[redirects]]
  from = "/services/refrigerator"
  to = "/services/refrigerator-repair"
  status = 301

[[redirects]]
  from = "/services/washer"
  to = "/services/washing-machine-repair"
  status = 301

[[redirects]]
  from = "/services/dryer"
  to = "/services/dryer-repair"
  status = 301

[[redirects]]
  from = "/services/oven"
  to = "/services/oven-repair"
  status = 301

[[redirects]]
  from = "/services/dishwasher"
  to = "/services/dishwasher-repair"
  status = 301

[[redirects]]
  from = "/services/microwave"
  to = "/services/microwave-repair"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force HTTPS redirects
[[redirects]]
  from = "http://naplesappliancerepair.xyz/*"
  to = "https://naplesappliancerepair.xyz/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.naplesappliancerepair.xyz/*"
  to = "https://naplesappliancerepair.xyz/:splat"
  status = 301
  force = true

# Redirect www to non-www
[[redirects]]
  from = "https://www.naplesappliancerepair.xyz/*"
  to = "https://naplesappliancerepair.xyz/:splat"
  status = 301
  force = true

[build.environment]
  NODE_VERSION = "18"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"