# Netlify configuration for Naples Appliance Repair SPA

# Build configuration
[build]
  command = "npm run build && node netlify-build.mjs"
  publish = "dist/public"
  environment = { NODE_VERSION = "20" }

# SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Cache configuration for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache configuration for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"